[package]
name = "tx"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.11"
csv = "1.3"
serde =  { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
rust_decimal = "1.35"
